app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

quiz/urls.py
from django.urls import path
from .views import ExamListView, ExamDetailView, ExamResultListView

app_name = 'quizzes'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('results/', ExamResultListView.as_view(), name='result_list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
]

quiz/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import BaseModel
from core.utils import generate_uuid


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 20

    class LEVEL(models.IntegerChoices):
        BASIC = 0, 'Basic'
        MIDDLE = 1, 'Middle'
        ADVANCED = 2, 'Advanced'

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def __str__(self):
        return self.title


class Question(BaseModel):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=2048)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.text


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(get_user_model(), related_name='results', on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(null=True)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

quiz/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Exam


class ExamListView(LoginRequiredMixin, ListView):
    model = Exam
    template_name = 'exams/list.html'
    context_object_name = 'exams'


class ExamDetailView(LoginRequiredMixin, DetailView):
    model = Exam
    template_name = 'exams/details.html'
    context_object_name = 'exam'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


class ExamResultListView(LoginRequiredMixin, ListView):
    model = Result
    template_name = 'results/list.html'
    context_object_name = 'results'
    paginate_by = 5

    def get_queryset(self):
        user = self.request.user
        return Result.objects.filter(user=user)

quiz/templates/exams/details.html
{% extends 'base.html' %}

{% block title %}
Описание теста
{% endblock %}

{% block header %}
Тест: {{ exam.title }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <table class="table table-striped">
                <tbody>
                <tr>
                    <td>Описание</td>
                    <td>{{ exam.description }}</td>
                </tr>
                <tr>
                    <td>Кол-во вопросов</td>
                    <td>{{ exam.questions.count }}</td>
                    {#
                    <td>{{ exam.questions_count }}</td>
                    #}
                </tr>
                <tr>
                    <td>Кол-во запусков</td>
                    <td>{{ exam.results.count }}</td>
                </tr>
                <tr>
                    <td>Лучший результат</td>
                    <td>N/A</td>
                </tr>
                <tr>
                    <td>Кто получил лучший результат</td>
                    <td>N/A</td>
                </tr>
                <tr>
                    <td>Последний запуск</td>
                    <td>N/A</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <a class="btn btn-primary" href="{% url 'quizzes:list' %}">Вернуться к списку тестов</a>
    </div>
</div>
{% endblock %}

quiz/templates/exams/list.html
{% extends 'base.html' %}

{% block title %}
    Список тестов
{% endblock %}

{% block header %}
    Список тестов.
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quizzes:details' uuid=exam.uuid %}">Подробнее</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="p-1 m-1">
            {% include 'includes/pagination.html' %}
        </div>
    {% else %}
        <p>Тестов ещё нет здесь!</p>
    {% endif %}
{% endblock %}